services:
  db:
    image: postgres:16
    container_name: jobboard_db
    restart: always
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
      POSTGRES_DB: jobboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobboard_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: jobboard_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: jobuser
      DB_PASSWORD: jobpass
      DB_NAME: jobboard
    depends_on:
      - db

volumes:
  db_data: